import dayjs from 'dayjs';

const now = dayjs();

let hour = -2;

const getMockDate = () => {
  hour++;
  return now.startOf('hour').add(hour, 'hour').toISOString();
};

const mockMetOfficeJSON = {
  type: 'FeatureCollection',
  features: [
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-0.050960000000000005, 51.48593, 15.0],
      },
      properties: {
        requestPointDistance: 1383.1984,
        modelRunDate: '2022-05-18T07:00Z',
        timeSeries: [
          {
            time: getMockDate(),
            screenTemperature: 13.97,
            maxScreenAirTemp: 13.98,
            minScreenAirTemp: 12.42,
            screenDewPointTemperature: 10.74,
            feelsLikeTemperature: 13.01,
            windSpeed10m: 2.88,
            windDirectionFrom10m: 245,
            windGustSpeed10m: 3.46,
            max10mWindGust: 3.55,
            visibility: 10840,
            screenRelativeHumidity: 80.39,
            mslp: 102120,
            uvIndex: 2,
            significantWeatherCode: 3,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: getMockDate(),
            screenTemperature: 14.09,
            maxScreenAirTemp: 14.1,
            minScreenAirTemp: 13.97,
            screenDewPointTemperature: 10.15,
            feelsLikeTemperature: 13.1,
            windSpeed10m: 2.86,
            windDirectionFrom10m: 234,
            windGustSpeed10m: 3.63,
            max10mWindGust: 3.85,
            visibility: 10787,
            screenRelativeHumidity: 76.83,
            mslp: 102188,
            uvIndex: 3,
            significantWeatherCode: 3,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 1,
          },
          {
            time: getMockDate(),
            screenTemperature: 22,
            maxScreenAirTemp: 15.28,
            minScreenAirTemp: 14.09,
            screenDewPointTemperature: 9.39,
            feelsLikeTemperature: 14.57,
            windSpeed10m: 2.31,
            windDirectionFrom10m: 234,
            windGustSpeed10m: 3.19,
            max10mWindGust: 3.84,
            visibility: 12538,
            screenRelativeHumidity: 67.66,
            mslp: 102184,
            uvIndex: 4,
            significantWeatherCode: 10,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 49,
          },
          {
            time: getMockDate(),
            screenTemperature: 17.03,
            maxScreenAirTemp: 17.03,
            minScreenAirTemp: 15.28,
            screenDewPointTemperature: 9.18,
            feelsLikeTemperature: 16.63,
            windSpeed10m: 1.67,
            windDirectionFrom10m: 213,
            windGustSpeed10m: 2.7,
            max10mWindGust: 3.2,
            visibility: 14503,
            screenRelativeHumidity: 59.68,
            mslp: 102161,
            uvIndex: 5,
            significantWeatherCode: 3,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: getMockDate(),
            screenTemperature: 18.99,
            maxScreenAirTemp: 19.0,
            minScreenAirTemp: 17.03,
            screenDewPointTemperature: 8.95,
            feelsLikeTemperature: 18.27,
            windSpeed10m: 1.84,
            windDirectionFrom10m: 197,
            windGustSpeed10m: 3.25,
            max10mWindGust: 3.27,
            visibility: 18043,
            screenRelativeHumidity: 52.0,
            mslp: 102120,
            uvIndex: 6,
            significantWeatherCode: 3,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: getMockDate(),
            screenTemperature: 20.91,
            maxScreenAirTemp: 20.92,
            minScreenAirTemp: 18.99,
            screenDewPointTemperature: 8.37,
            feelsLikeTemperature: 19.45,
            windSpeed10m: 2.79,
            windDirectionFrom10m: 190,
            windGustSpeed10m: 4.52,
            max10mWindGust: 4.52,
            visibility: 22506,
            screenRelativeHumidity: 44.31,
            mslp: 102080,
            uvIndex: 6,
            significantWeatherCode: 3,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: getMockDate(),
            screenTemperature: 22.27,
            maxScreenAirTemp: 22.28,
            minScreenAirTemp: 20.91,
            screenDewPointTemperature: 7.54,
            feelsLikeTemperature: 20.28,
            windSpeed10m: 3.48,
            windDirectionFrom10m: 184,
            windGustSpeed10m: 5.72,
            max10mWindGust: 5.72,
            visibility: 24528,
            screenRelativeHumidity: 38.71,
            mslp: 102010,
            uvIndex: 5,
            significantWeatherCode: 3,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: getMockDate(),
            screenTemperature: 22.93,
            maxScreenAirTemp: 22.94,
            minScreenAirTemp: 22.27,
            screenDewPointTemperature: 6.34,
            feelsLikeTemperature: 20.29,
            windSpeed10m: 4.27,
            windDirectionFrom10m: 189,
            windGustSpeed10m: 7.04,
            max10mWindGust: 7.04,
            visibility: 27165,
            screenRelativeHumidity: 34.21,
            mslp: 101952,
            uvIndex: 4,
            significantWeatherCode: 3,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: getMockDate(),
            screenTemperature: 22.65,
            maxScreenAirTemp: 22.93,
            minScreenAirTemp: 22.64,
            screenDewPointTemperature: 6.08,
            feelsLikeTemperature: 19.98,
            windSpeed10m: 4.23,
            windDirectionFrom10m: 186,
            windGustSpeed10m: 7.1,
            max10mWindGust: 7.34,
            visibility: 28193,
            screenRelativeHumidity: 34.11,
            mslp: 101906,
            uvIndex: 3,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 5,
          },
          {
            time: getMockDate(),
            screenTemperature: 22.13,
            maxScreenAirTemp: 22.65,
            minScreenAirTemp: 22.13,
            screenDewPointTemperature: 5.75,
            feelsLikeTemperature: 19.53,
            windSpeed10m: 4.05,
            windDirectionFrom10m: 177,
            windGustSpeed10m: 6.66,
            max10mWindGust: 6.9,
            visibility: 30323,
            screenRelativeHumidity: 34.42,
            mslp: 101840,
            uvIndex: 2,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 5,
          },
          {
            time: getMockDate(),
            screenTemperature: 21.8,
            maxScreenAirTemp: 22.13,
            minScreenAirTemp: 21.77,
            screenDewPointTemperature: 6.59,
            feelsLikeTemperature: 19.48,
            windSpeed10m: 3.76,
            windDirectionFrom10m: 163,
            windGustSpeed10m: 6.47,
            max10mWindGust: 6.47,
            visibility: 30528,
            screenRelativeHumidity: 37.3,
            mslp: 101776,
            uvIndex: 2,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 5,
          },
          {
            time: getMockDate(),
            screenTemperature: 21.48,
            maxScreenAirTemp: 21.87,
            minScreenAirTemp: 21.47,
            screenDewPointTemperature: 7.03,
            feelsLikeTemperature: 19.06,
            windSpeed10m: 3.99,
            windDirectionFrom10m: 153,
            windGustSpeed10m: 7.23,
            max10mWindGust: 7.23,
            visibility: 31219,
            screenRelativeHumidity: 39.21,
            mslp: 101735,
            uvIndex: 1,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 5,
          },
          {
            time: getMockDate(),
            screenTemperature: 20.59,
            maxScreenAirTemp: 21.48,
            minScreenAirTemp: 20.58,
            screenDewPointTemperature: 7.01,
            feelsLikeTemperature: 18.21,
            windSpeed10m: 3.9,
            windDirectionFrom10m: 132,
            windGustSpeed10m: 7.21,
            max10mWindGust: 7.24,
            visibility: 31611,
            screenRelativeHumidity: 41.72,
            mslp: 101679,
            uvIndex: 1,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 5,
          },
          {
            time: getMockDate(),
            screenTemperature: 19.58,
            maxScreenAirTemp: 20.59,
            minScreenAirTemp: 19.57,
            screenDewPointTemperature: 7.3,
            feelsLikeTemperature: 17.51,
            windSpeed10m: 3.6,
            windDirectionFrom10m: 108,
            windGustSpeed10m: 6.58,
            max10mWindGust: 7.04,
            visibility: 31806,
            screenRelativeHumidity: 45.39,
            mslp: 101606,
            uvIndex: 0,
            significantWeatherCode: 13,
            precipitationRate: 3.05,
            totalPrecipAmount: 0.24,
            totalSnowAmount: 0,
            probOfPrecipitation: 55,
          },
          {
            time: getMockDate(),
            screenTemperature: 18.68,
            maxScreenAirTemp: 19.58,
            minScreenAirTemp: 18.66,
            screenDewPointTemperature: 9.5,
            feelsLikeTemperature: 16.94,
            windSpeed10m: 3.72,
            windDirectionFrom10m: 108,
            windGustSpeed10m: 7.39,
            max10mWindGust: 8.2,
            visibility: 13449,
            screenRelativeHumidity: 55.69,
            mslp: 101548,
            uvIndex: 0,
            significantWeatherCode: 15,
            precipitationRate: 3.07,
            totalPrecipAmount: 0.75,
            totalSnowAmount: 0,
            probOfPrecipitation: 79,
          },
          {
            time: getMockDate(),
            screenTemperature: 17.75,
            maxScreenAirTemp: 18.68,
            minScreenAirTemp: 17.73,
            screenDewPointTemperature: 11.26,
            feelsLikeTemperature: 16.32,
            windSpeed10m: 3.76,
            windDirectionFrom10m: 119,
            windGustSpeed10m: 8.14,
            max10mWindGust: 8.31,
            visibility: 11486,
            screenRelativeHumidity: 66.87,
            mslp: 101500,
            uvIndex: 0,
            significantWeatherCode: 15,
            precipitationRate: 8.34,
            totalPrecipAmount: 1.99,
            totalSnowAmount: 0,
            probOfPrecipitation: 91,
          },
          {
            time: getMockDate(),
            screenTemperature: 17.69,
            maxScreenAirTemp: 17.93,
            minScreenAirTemp: 17.54,
            screenDewPointTemperature: 13.32,
            feelsLikeTemperature: 16.31,
            windSpeed10m: 4.2,
            windDirectionFrom10m: 137,
            windGustSpeed10m: 9.0,
            max10mWindGust: 14.42,
            visibility: 4974,
            screenRelativeHumidity: 76.02,
            mslp: 101514,
            uvIndex: 0,
            significantWeatherCode: 15,
            precipitationRate: 9.19,
            totalPrecipAmount: 4.61,
            totalSnowAmount: 0,
            probOfPrecipitation: 90,
          },
          {
            time: getMockDate(),
            screenTemperature: 17.16,
            maxScreenAirTemp: 17.69,
            minScreenAirTemp: 17.09,
            screenDewPointTemperature: 14.45,
            feelsLikeTemperature: 17.28,
            windSpeed10m: 1.93,
            windDirectionFrom10m: 27,
            windGustSpeed10m: 3.98,
            max10mWindGust: 8.41,
            visibility: 25468,
            screenRelativeHumidity: 84.33,
            mslp: 101450,
            uvIndex: 0,
            significantWeatherCode: 13,
            precipitationRate: 6.77,
            totalPrecipAmount: 1.76,
            totalSnowAmount: 0,
            probOfPrecipitation: 69,
          },
          {
            time: getMockDate(),
            screenTemperature: 16.8,
            maxScreenAirTemp: 17.16,
            minScreenAirTemp: 16.8,
            screenDewPointTemperature: 14.39,
            feelsLikeTemperature: 16.97,
            windSpeed10m: 1.82,
            windDirectionFrom10m: 231,
            windGustSpeed10m: 3.95,
            max10mWindGust: 4.46,
            visibility: 21070,
            screenRelativeHumidity: 85.85,
            mslp: 101437,
            uvIndex: 0,
            significantWeatherCode: 12,
            precipitationRate: 5.67,
            totalPrecipAmount: 0.21,
            totalSnowAmount: 0,
            probOfPrecipitation: 39,
          },
          {
            time: getMockDate(),
            screenTemperature: 16.44,
            maxScreenAirTemp: 16.8,
            minScreenAirTemp: 16.4,
            screenDewPointTemperature: 14.15,
            feelsLikeTemperature: 16.56,
            windSpeed10m: 1.82,
            windDirectionFrom10m: 189,
            windGustSpeed10m: 3.33,
            max10mWindGust: 3.85,
            visibility: 20819,
            screenRelativeHumidity: 86.44,
            mslp: 101437,
            uvIndex: 0,
            significantWeatherCode: 9,
            precipitationRate: 0.65,
            totalPrecipAmount: 0.24,
            totalSnowAmount: 0,
            probOfPrecipitation: 30,
          },
          {
            time: getMockDate(),
            screenTemperature: 15.97,
            maxScreenAirTemp: 16.44,
            minScreenAirTemp: 15.95,
            screenDewPointTemperature: 14.17,
            feelsLikeTemperature: 16.12,
            windSpeed10m: 1.7,
            windDirectionFrom10m: 261,
            windGustSpeed10m: 3.36,
            max10mWindGust: 3.53,
            visibility: 15792,
            screenRelativeHumidity: 89.21,
            mslp: 101453,
            uvIndex: 0,
            significantWeatherCode: 9,
            precipitationRate: 1.52,
            totalPrecipAmount: 0.09,
            totalSnowAmount: 0,
            probOfPrecipitation: 33,
          },
          {
            time: getMockDate(),
            screenTemperature: 15.54,
            maxScreenAirTemp: 15.97,
            minScreenAirTemp: 15.52,
            screenDewPointTemperature: 13.35,
            feelsLikeTemperature: 14.67,
            windSpeed10m: 3.33,
            windDirectionFrom10m: 291,
            windGustSpeed10m: 6.26,
            max10mWindGust: 6.41,
            visibility: 17115,
            screenRelativeHumidity: 86.97,
            mslp: 101524,
            uvIndex: 0,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 6,
          },
          {
            time: getMockDate(),
            screenTemperature: 14.91,
            maxScreenAirTemp: 15.54,
            minScreenAirTemp: 14.9,
            screenDewPointTemperature: 12.51,
            feelsLikeTemperature: 14.03,
            windSpeed10m: 3.13,
            windDirectionFrom10m: 297,
            windGustSpeed10m: 5.74,
            max10mWindGust: 6.14,
            visibility: 19999,
            screenRelativeHumidity: 85.63,
            mslp: 101620,
            uvIndex: 1,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 4,
          },
          {
            time: getMockDate(),
            screenTemperature: 14.73,
            maxScreenAirTemp: 14.91,
            minScreenAirTemp: 14.68,
            screenDewPointTemperature: 11.91,
            feelsLikeTemperature: 13.75,
            windSpeed10m: 3.18,
            windDirectionFrom10m: 300,
            windGustSpeed10m: 5.8,
            max10mWindGust: 5.8,
            visibility: 20145,
            screenRelativeHumidity: 83.28,
            mslp: 101690,
            uvIndex: 1,
            significantWeatherCode: 3,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: getMockDate(),
            screenTemperature: 15.26,
            maxScreenAirTemp: 15.27,
            minScreenAirTemp: 14.73,
            screenDewPointTemperature: 11.01,
            feelsLikeTemperature: 14.18,
            windSpeed10m: 3.24,
            windDirectionFrom10m: 288,
            windGustSpeed10m: 5.88,
            max10mWindGust: 5.88,
            visibility: 20697,
            screenRelativeHumidity: 75.86,
            mslp: 101754,
            uvIndex: 2,
            significantWeatherCode: 3,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: getMockDate(),
            screenTemperature: 15.88,
            maxScreenAirTemp: 15.9,
            minScreenAirTemp: 15.26,
            screenDewPointTemperature: 10.27,
            feelsLikeTemperature: 14.88,
            windSpeed10m: 2.93,
            windDirectionFrom10m: 286,
            windGustSpeed10m: 5.3,
            max10mWindGust: 5.58,
            visibility: 22088,
            screenRelativeHumidity: 69.45,
            mslp: 101801,
            uvIndex: 3,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 4,
          },
          {
            time: getMockDate(),
            screenTemperature: 16.78,
            maxScreenAirTemp: 16.8,
            minScreenAirTemp: 15.88,
            screenDewPointTemperature: 9.55,
            feelsLikeTemperature: 15.65,
            windSpeed10m: 2.98,
            windDirectionFrom10m: 276,
            windGustSpeed10m: 5.37,
            max10mWindGust: 5.37,
            visibility: 22985,
            screenRelativeHumidity: 62.52,
            mslp: 101867,
            uvIndex: 4,
            significantWeatherCode: 3,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: getMockDate(),
            screenTemperature: 17.98,
            maxScreenAirTemp: 18.01,
            minScreenAirTemp: 16.78,
            screenDewPointTemperature: 8.62,
            feelsLikeTemperature: 16.51,
            windSpeed10m: 3.2,
            windDirectionFrom10m: 265,
            windGustSpeed10m: 5.83,
            max10mWindGust: 5.83,
            visibility: 24073,
            screenRelativeHumidity: 54.7,
            mslp: 101923,
            uvIndex: 5,
            significantWeatherCode: 1,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: getMockDate(),
            screenTemperature: 19.08,
            maxScreenAirTemp: 19.09,
            minScreenAirTemp: 17.98,
            screenDewPointTemperature: 7.88,
            feelsLikeTemperature: 17.38,
            windSpeed10m: 3.18,
            windDirectionFrom10m: 263,
            windGustSpeed10m: 6.02,
            max10mWindGust: 6.02,
            visibility: 26611,
            screenRelativeHumidity: 48.79,
            mslp: 101960,
            uvIndex: 6,
            significantWeatherCode: 3,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: getMockDate(),
            screenTemperature: 20.32,
            maxScreenAirTemp: 20.33,
            minScreenAirTemp: 19.08,
            screenDewPointTemperature: 6.68,
            feelsLikeTemperature: 18.23,
            windSpeed10m: 3.45,
            windDirectionFrom10m: 256,
            windGustSpeed10m: 6.51,
            max10mWindGust: 6.51,
            visibility: 28331,
            screenRelativeHumidity: 41.47,
            mslp: 101971,
            uvIndex: 7,
            significantWeatherCode: 1,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: getMockDate(),
            screenTemperature: 21.05,
            maxScreenAirTemp: 21.06,
            minScreenAirTemp: 20.32,
            screenDewPointTemperature: 5.68,
            feelsLikeTemperature: 19.01,
            windSpeed10m: 3.18,
            windDirectionFrom10m: 256,
            windGustSpeed10m: 6.09,
            max10mWindGust: 6.09,
            visibility: 29213,
            screenRelativeHumidity: 37.19,
            mslp: 101959,
            uvIndex: 5,
            significantWeatherCode: 3,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 1,
          },
          {
            time: '2022-05-19T14:00Z',
            screenTemperature: 21.54,
            maxScreenAirTemp: 21.55,
            minScreenAirTemp: 21.05,
            screenDewPointTemperature: 5.11,
            feelsLikeTemperature: 19.52,
            windSpeed10m: 3.04,
            windDirectionFrom10m: 256,
            windGustSpeed10m: 5.85,
            max10mWindGust: 5.85,
            visibility: 29904,
            screenRelativeHumidity: 34.7,
            mslp: 101957,
            uvIndex: 4,
            significantWeatherCode: 3,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: getMockDate(),
            screenTemperature: 22.03,
            maxScreenAirTemp: 22.04,
            minScreenAirTemp: 21.54,
            screenDewPointTemperature: 4.94,
            feelsLikeTemperature: 20.04,
            windSpeed10m: 2.94,
            windDirectionFrom10m: 252,
            windGustSpeed10m: 5.71,
            max10mWindGust: 5.71,
            visibility: 30184,
            screenRelativeHumidity: 33.1,
            mslp: 101950,
            uvIndex: 3,
            significantWeatherCode: 3,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 1,
          },
          {
            time: getMockDate(),
            screenTemperature: 21.86,
            maxScreenAirTemp: 22.03,
            minScreenAirTemp: 21.86,
            screenDewPointTemperature: 5.02,
            feelsLikeTemperature: 19.88,
            windSpeed10m: 2.96,
            windDirectionFrom10m: 248,
            windGustSpeed10m: 5.77,
            max10mWindGust: 5.77,
            visibility: 30657,
            screenRelativeHumidity: 33.62,
            mslp: 101953,
            uvIndex: 3,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 4,
          },
          {
            time: getMockDate(),
            screenTemperature: 21.75,
            maxScreenAirTemp: 21.86,
            minScreenAirTemp: 21.71,
            screenDewPointTemperature: 5.13,
            feelsLikeTemperature: 19.79,
            windSpeed10m: 2.92,
            windDirectionFrom10m: 242,
            windGustSpeed10m: 5.7,
            max10mWindGust: 5.7,
            visibility: 30836,
            screenRelativeHumidity: 34.13,
            mslp: 101947,
            uvIndex: 2,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 4,
          },
          {
            time: getMockDate(),
            screenTemperature: 21.22,
            maxScreenAirTemp: 21.75,
            minScreenAirTemp: 21.21,
            screenDewPointTemperature: 5.92,
            feelsLikeTemperature: 19.07,
            windSpeed10m: 3.34,
            windDirectionFrom10m: 227,
            windGustSpeed10m: 6.23,
            max10mWindGust: 6.23,
            visibility: 30165,
            screenRelativeHumidity: 37.16,
            mslp: 101935,
            uvIndex: 1,
            significantWeatherCode: 3,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 1,
          },
          {
            time: getMockDate(),
            screenTemperature: 20.03,
            maxScreenAirTemp: 21.22,
            minScreenAirTemp: 20.02,
            screenDewPointTemperature: 6.3,
            feelsLikeTemperature: 17.53,
            windSpeed10m: 4.04,
            windDirectionFrom10m: 220,
            windGustSpeed10m: 7.44,
            max10mWindGust: 8.14,
            visibility: 30626,
            screenRelativeHumidity: 41.15,
            mslp: 101980,
            uvIndex: 1,
            significantWeatherCode: 3,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 1,
          },
          {
            time: getMockDate(),
            screenTemperature: 18.81,
            maxScreenAirTemp: 20.03,
            minScreenAirTemp: 18.79,
            screenDewPointTemperature: 6.5,
            feelsLikeTemperature: 16.69,
            windSpeed10m: 3.71,
            windDirectionFrom10m: 223,
            windGustSpeed10m: 6.88,
            max10mWindGust: 7.6,
            visibility: 29629,
            screenRelativeHumidity: 45.17,
            mslp: 102023,
            uvIndex: 0,
            significantWeatherCode: 2,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 1,
          },
          {
            time: getMockDate(),
            screenTemperature: 17.86,
            maxScreenAirTemp: 18.81,
            minScreenAirTemp: 17.86,
            screenDewPointTemperature: 6.78,
            feelsLikeTemperature: 16.03,
            windSpeed10m: 3.48,
            windDirectionFrom10m: 226,
            windGustSpeed10m: 6.41,
            max10mWindGust: 6.68,
            visibility: 29231,
            screenRelativeHumidity: 48.79,
            mslp: 102063,
            uvIndex: 0,
            significantWeatherCode: 2,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: getMockDate(),
            screenTemperature: 17.17,
            maxScreenAirTemp: 17.86,
            minScreenAirTemp: 17.17,
            screenDewPointTemperature: 6.5,
            feelsLikeTemperature: 15.52,
            windSpeed10m: 3.24,
            windDirectionFrom10m: 229,
            windGustSpeed10m: 5.95,
            max10mWindGust: 6.0,
            visibility: 29296,
            screenRelativeHumidity: 50.17,
            mslp: 102065,
            uvIndex: 0,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 5,
          },
          {
            time: getMockDate(),
            screenTemperature: 16.45,
            maxScreenAirTemp: 17.17,
            minScreenAirTemp: 16.44,
            screenDewPointTemperature: 6.58,
            feelsLikeTemperature: 15.18,
            windSpeed10m: 2.72,
            windDirectionFrom10m: 231,
            windGustSpeed10m: 5.04,
            max10mWindGust: 5.94,
            visibility: 28705,
            screenRelativeHumidity: 52.85,
            mslp: 102045,
            uvIndex: 0,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 4,
          },
          {
            time: getMockDate(),
            screenTemperature: 15.84,
            maxScreenAirTemp: 16.45,
            minScreenAirTemp: 15.83,
            screenDewPointTemperature: 6.72,
            feelsLikeTemperature: 14.77,
            windSpeed10m: 2.51,
            windDirectionFrom10m: 231,
            windGustSpeed10m: 4.53,
            max10mWindGust: 4.53,
            visibility: 28355,
            screenRelativeHumidity: 55.47,
            mslp: 102025,
            uvIndex: 0,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 4,
          },
          {
            time: getMockDate(),
            screenTemperature: 15.28,
            maxScreenAirTemp: 15.84,
            minScreenAirTemp: 15.28,
            screenDewPointTemperature: 7.21,
            feelsLikeTemperature: 14.36,
            windSpeed10m: 2.33,
            windDirectionFrom10m: 229,
            windGustSpeed10m: 4.24,
            max10mWindGust: 4.24,
            visibility: 27577,
            screenRelativeHumidity: 59.4,
            mslp: 101983,
            uvIndex: 0,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 4,
          },
          {
            time: getMockDate(),
            screenTemperature: 14.82,
            maxScreenAirTemp: 15.28,
            minScreenAirTemp: 14.82,
            screenDewPointTemperature: 7.59,
            feelsLikeTemperature: 13.98,
            windSpeed10m: 2.26,
            windDirectionFrom10m: 227,
            windGustSpeed10m: 4.11,
            max10mWindGust: 4.18,
            visibility: 25670,
            screenRelativeHumidity: 62.8,
            mslp: 101951,
            uvIndex: 0,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 3,
          },
          {
            time: getMockDate(),
            screenTemperature: 14.38,
            maxScreenAirTemp: 14.82,
            minScreenAirTemp: 14.37,
            screenDewPointTemperature: 7.81,
            feelsLikeTemperature: 13.63,
            windSpeed10m: 2.19,
            windDirectionFrom10m: 227,
            windGustSpeed10m: 3.93,
            max10mWindGust: 4.6,
            visibility: 24862,
            screenRelativeHumidity: 65.33,
            mslp: 101928,
            uvIndex: 0,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 4,
          },
          {
            time: getMockDate(),
            screenTemperature: 14.15,
            maxScreenAirTemp: 14.38,
            minScreenAirTemp: 14.12,
            screenDewPointTemperature: 8.05,
            feelsLikeTemperature: 13.51,
            windSpeed10m: 2.01,
            windDirectionFrom10m: 227,
            windGustSpeed10m: 3.78,
            max10mWindGust: 4.7,
            visibility: 23862,
            screenRelativeHumidity: 67.48,
            mslp: 101920,
            uvIndex: 0,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 4,
          },
          {
            time: getMockDate(),
            screenTemperature: 14.07,
            maxScreenAirTemp: 14.15,
            minScreenAirTemp: 14.04,
            screenDewPointTemperature: 8.19,
            feelsLikeTemperature: 13.61,
            windSpeed10m: 1.74,
            windDirectionFrom10m: 219,
            windGustSpeed10m: 3.32,
            max10mWindGust: 4.2,
            visibility: 21380,
            screenRelativeHumidity: 68.44,
            mslp: 101913,
            uvIndex: 1,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 4,
          },
          {
            time: getMockDate(),
            screenTemperature: 14.09,
            screenDewPointTemperature: 8.32,
            feelsLikeTemperature: 13.67,
            windSpeed10m: 1.7,
            windDirectionFrom10m: 220,
            windGustSpeed10m: 3.28,
            visibility: 20545,
            screenRelativeHumidity: 68.93,
            mslp: 101904,
            uvIndex: 1,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            probOfPrecipitation: 5,
          },
          {
            time: getMockDate(),
            screenTemperature: 14.32,
            screenDewPointTemperature: 8.39,
            feelsLikeTemperature: 13.82,
            windSpeed10m: 1.83,
            windDirectionFrom10m: 227,
            windGustSpeed10m: 3.78,
            visibility: 21535,
            screenRelativeHumidity: 68.48,
            mslp: 101882,
            uvIndex: 1,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            probOfPrecipitation: 5,
          },
        ],
      },
    },
  ],
  parameters: [
    {
      totalSnowAmount: {
        type: 'Parameter',
        description: 'Total Snow Amount Over Previous Hour',
        unit: {
          label: 'millimetres',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'mm',
          },
        },
      },
      screenTemperature: {
        type: 'Parameter',
        description: 'Screen Air Temperature',
        unit: {
          label: 'degrees Celsius',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'Cel',
          },
        },
      },
      visibility: {
        type: 'Parameter',
        description: 'Visibility',
        unit: {
          label: 'metres',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'm',
          },
        },
      },
      windDirectionFrom10m: {
        type: 'Parameter',
        description: '10m Wind From Direction',
        unit: {
          label: 'degrees',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'deg',
          },
        },
      },
      precipitationRate: {
        type: 'Parameter',
        description: 'Precipitation Rate',
        unit: {
          label: 'millimetres per hour',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'mm/h',
          },
        },
      },
      maxScreenAirTemp: {
        type: 'Parameter',
        description: 'Maximum Screen Air Temperature Over Previous Hour',
        unit: {
          label: 'degrees Celsius',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'Cel',
          },
        },
      },
      feelsLikeTemperature: {
        type: 'Parameter',
        description: 'Feels Like Temperature',
        unit: {
          label: 'degrees Celsius',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'Cel',
          },
        },
      },
      screenDewPointTemperature: {
        type: 'Parameter',
        description: 'Screen Dew Point Temperature',
        unit: {
          label: 'degrees Celsius',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'Cel',
          },
        },
      },
      screenRelativeHumidity: {
        type: 'Parameter',
        description: 'Screen Relative Humidity',
        unit: {
          label: 'percentage',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: '%',
          },
        },
      },
      windSpeed10m: {
        type: 'Parameter',
        description: '10m Wind Speed',
        unit: {
          label: 'metres per second',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'm/s',
          },
        },
      },
      probOfPrecipitation: {
        type: 'Parameter',
        description: 'Probability of Precipitation',
        unit: {
          label: 'percentage',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: '%',
          },
        },
      },
      max10mWindGust: {
        type: 'Parameter',
        description: 'Maximum 10m Wind Gust Speed Over Previous Hour',
        unit: {
          label: 'metres per second',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'm/s',
          },
        },
      },
      significantWeatherCode: {
        type: 'Parameter',
        description: 'Significant Weather Code',
        unit: {
          label: 'dimensionless',
          symbol: {
            value:
              'https://metoffice.apiconnect.ibmcloud.com/metoffice/production/',
            type: '1',
          },
        },
      },
      minScreenAirTemp: {
        type: 'Parameter',
        description: 'Minimum Screen Air Temperature Over Previous Hour',
        unit: {
          label: 'degrees Celsius',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'Cel',
          },
        },
      },
      totalPrecipAmount: {
        type: 'Parameter',
        description: 'Total Precipitation Amount Over Previous Hour',
        unit: {
          label: 'millimetres',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'mm',
          },
        },
      },
      mslp: {
        type: 'Parameter',
        description: 'Mean Sea Level Pressure',
        unit: {
          label: 'pascals',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'Pa',
          },
        },
      },
      windGustSpeed10m: {
        type: 'Parameter',
        description: '10m Wind Gust Speed',
        unit: {
          label: 'metres per second',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'm/s',
          },
        },
      },
      uvIndex: {
        type: 'Parameter',
        description: 'UV Index',
        unit: {
          label: 'dimensionless',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: '1',
          },
        },
      },
    },
  ],
};

const getMockMetOfficeJSON = () => mockMetOfficeJSON;

export default getMockMetOfficeJSON;
