// import { SpotForecastFeatureCollection } from '../api/typescript-fetch-client/api';
import getMockDate from './mockDate.mjs';

const mockHourlyMetOfficeJSON /* : SpotForecastFeatureCollection */ = {
  type: 'FeatureCollection',
  features: [
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-0.050960000000000005, 51.48593, 15.0],
      },
      properties: {
        requestPointDistance: 1383.1984,
        modelRunDate: '2023-07-10T17:00Z',
        timeSeries: [
          {
            time: getMockDate(),
            screenTemperature: 21.99,
            maxScreenAirTemp: 22.24,
            minScreenAirTemp: 21.98,
            screenDewPointTemperature: 12.34,
            feelsLikeTemperature: 19.0,
            windSpeed10m: 6.17,
            windDirectionFrom10m: 227,
            windGustSpeed10m: 12.86,
            max10mWindGust: 12.86,
            visibility: 21828,
            screenRelativeHumidity: 53.73,
            mslp: 101750,
            uvIndex: 2,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 5,
          },
          {
            time: '2023-07-10T18:00Z',
            screenTemperature: 22.12,
            maxScreenAirTemp: 22.13,
            minScreenAirTemp: 21.99,
            screenDewPointTemperature: 12.63,
            feelsLikeTemperature: 18.88,
            windSpeed10m: 6.65,
            windDirectionFrom10m: 215,
            windGustSpeed10m: 12.93,
            max10mWindGust: 12.93,
            visibility: 20444,
            screenRelativeHumidity: 54.45,
            mslp: 101707,
            uvIndex: 1,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 4,
          },
          {
            time: '2023-07-10T19:00Z',
            screenTemperature: 21.6,
            maxScreenAirTemp: 22.12,
            minScreenAirTemp: 21.59,
            screenDewPointTemperature: 13.18,
            feelsLikeTemperature: 18.67,
            windSpeed10m: 6.31,
            windDirectionFrom10m: 217,
            windGustSpeed10m: 12.28,
            max10mWindGust: 12.87,
            visibility: 18768,
            screenRelativeHumidity: 58.39,
            mslp: 101656,
            uvIndex: 1,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 4,
          },
          {
            time: '2023-07-10T20:00Z',
            screenTemperature: 20.59,
            maxScreenAirTemp: 21.6,
            minScreenAirTemp: 20.58,
            screenDewPointTemperature: 13.8,
            feelsLikeTemperature: 18.13,
            windSpeed10m: 5.73,
            windDirectionFrom10m: 208,
            windGustSpeed10m: 11.09,
            max10mWindGust: 11.91,
            visibility: 19122,
            screenRelativeHumidity: 64.84,
            mslp: 101633,
            uvIndex: 1,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 4,
          },
          {
            time: '2023-07-10T21:00Z',
            screenTemperature: 20.14,
            maxScreenAirTemp: 20.59,
            minScreenAirTemp: 20.13,
            screenDewPointTemperature: 13.87,
            feelsLikeTemperature: 18.11,
            windSpeed10m: 5.1,
            windDirectionFrom10m: 197,
            windGustSpeed10m: 10.1,
            max10mWindGust: 10.52,
            visibility: 17612,
            screenRelativeHumidity: 66.93,
            mslp: 101580,
            uvIndex: 0,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 7,
          },
          {
            time: '2023-07-10T22:00Z',
            screenTemperature: 19.82,
            maxScreenAirTemp: 20.14,
            minScreenAirTemp: 19.8,
            screenDewPointTemperature: 14.18,
            feelsLikeTemperature: 18.35,
            windSpeed10m: 4.36,
            windDirectionFrom10m: 193,
            windGustSpeed10m: 8.8,
            max10mWindGust: 9.58,
            visibility: 18674,
            screenRelativeHumidity: 69.65,
            mslp: 101520,
            uvIndex: 0,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 7,
          },
          {
            time: '2023-07-10T23:00Z',
            screenTemperature: 19.45,
            maxScreenAirTemp: 19.82,
            minScreenAirTemp: 19.44,
            screenDewPointTemperature: 14.47,
            feelsLikeTemperature: 18.14,
            windSpeed10m: 4.24,
            windDirectionFrom10m: 184,
            windGustSpeed10m: 8.65,
            max10mWindGust: 8.65,
            visibility: 18742,
            screenRelativeHumidity: 72.68,
            mslp: 101460,
            uvIndex: 0,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 10,
          },
          {
            time: '2023-07-11T00:00Z',
            screenTemperature: 19.11,
            maxScreenAirTemp: 19.45,
            minScreenAirTemp: 19.1,
            screenDewPointTemperature: 14.51,
            feelsLikeTemperature: 17.85,
            windSpeed10m: 4.23,
            windDirectionFrom10m: 182,
            windGustSpeed10m: 9.3,
            max10mWindGust: 9.3,
            visibility: 19748,
            screenRelativeHumidity: 74.47,
            mslp: 101400,
            uvIndex: 0,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 50,
          },
          {
            time: '2023-07-11T01:00Z',
            screenTemperature: 19.41,
            maxScreenAirTemp: 19.42,
            minScreenAirTemp: 19.11,
            screenDewPointTemperature: 14.32,
            feelsLikeTemperature: 17.48,
            windSpeed10m: 5.2,
            windDirectionFrom10m: 190,
            windGustSpeed10m: 11.21,
            max10mWindGust: 11.21,
            visibility: 22919,
            screenRelativeHumidity: 72.19,
            mslp: 101318,
            uvIndex: 0,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 9,
          },
          {
            time: '2023-07-11T02:00Z',
            screenTemperature: 19.31,
            maxScreenAirTemp: 19.41,
            minScreenAirTemp: 19.27,
            screenDewPointTemperature: 14.71,
            feelsLikeTemperature: 17.18,
            windSpeed10m: 5.66,
            windDirectionFrom10m: 199,
            windGustSpeed10m: 11.88,
            max10mWindGust: 12.17,
            visibility: 21844,
            screenRelativeHumidity: 74.6,
            mslp: 101234,
            uvIndex: 0,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 8,
          },
          {
            time: '2023-07-11T03:00Z',
            screenTemperature: 19.11,
            maxScreenAirTemp: 19.31,
            minScreenAirTemp: 19.09,
            screenDewPointTemperature: 15.14,
            feelsLikeTemperature: 16.93,
            windSpeed10m: 5.93,
            windDirectionFrom10m: 203,
            windGustSpeed10m: 12.27,
            max10mWindGust: 12.27,
            visibility: 24198,
            screenRelativeHumidity: 77.73,
            mslp: 101160,
            uvIndex: 0,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 16,
          },
          {
            time: '2023-07-11T04:00Z',
            screenTemperature: 18.78,
            maxScreenAirTemp: 19.11,
            minScreenAirTemp: 18.76,
            screenDewPointTemperature: 15.68,
            feelsLikeTemperature: 16.89,
            windSpeed10m: 5.7,
            windDirectionFrom10m: 208,
            windGustSpeed10m: 11.7,
            max10mWindGust: 12.27,
            visibility: 20673,
            screenRelativeHumidity: 82.18,
            mslp: 101110,
            uvIndex: 0,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 20,
          },
          {
            time: '2023-07-11T05:00Z',
            screenTemperature: 18.42,
            maxScreenAirTemp: 18.78,
            minScreenAirTemp: 18.4,
            screenDewPointTemperature: 15.85,
            feelsLikeTemperature: 16.76,
            windSpeed10m: 5.41,
            windDirectionFrom10m: 221,
            windGustSpeed10m: 11.0,
            max10mWindGust: 11.88,
            visibility: 16889,
            screenRelativeHumidity: 85.05,
            mslp: 101084,
            uvIndex: 1,
            significantWeatherCode: 12,
            precipitationRate: 0.22,
            totalPrecipAmount: 0.94,
            totalSnowAmount: 0,
            probOfPrecipitation: 52,
          },
          {
            time: '2023-07-11T06:00Z',
            screenTemperature: 18.09,
            maxScreenAirTemp: 18.42,
            minScreenAirTemp: 18.07,
            screenDewPointTemperature: 16.04,
            feelsLikeTemperature: 16.76,
            windSpeed10m: 4.92,
            windDirectionFrom10m: 225,
            windGustSpeed10m: 9.77,
            max10mWindGust: 10.98,
            visibility: 13372,
            screenRelativeHumidity: 87.89,
            mslp: 101066,
            uvIndex: 1,
            significantWeatherCode: 15,
            precipitationRate: 1.49,
            totalPrecipAmount: 0.18,
            totalSnowAmount: 0,
            probOfPrecipitation: 82,
          },
          {
            time: '2023-07-11T07:00Z',
            screenTemperature: 17.59,
            maxScreenAirTemp: 18.09,
            minScreenAirTemp: 17.58,
            screenDewPointTemperature: 15.26,
            feelsLikeTemperature: 16.36,
            windSpeed10m: 4.54,
            windDirectionFrom10m: 236,
            windGustSpeed10m: 9.18,
            max10mWindGust: 10.42,
            visibility: 8969,
            screenRelativeHumidity: 86.41,
            mslp: 101090,
            uvIndex: 2,
            significantWeatherCode: 14,
            precipitationRate: 1.3,
            totalPrecipAmount: 1.39,
            totalSnowAmount: 0,
            probOfPrecipitation: 65,
          },
          {
            time: '2023-07-11T08:00Z',
            screenTemperature: 17.61,
            maxScreenAirTemp: 17.64,
            minScreenAirTemp: 17.52,
            screenDewPointTemperature: 14.46,
            feelsLikeTemperature: 16.34,
            windSpeed10m: 4.34,
            windDirectionFrom10m: 227,
            windGustSpeed10m: 8.62,
            max10mWindGust: 8.72,
            visibility: 19511,
            screenRelativeHumidity: 82.04,
            mslp: 101084,
            uvIndex: 2,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 15,
          },
          {
            time: '2023-07-11T09:00Z',
            screenTemperature: 17.81,
            maxScreenAirTemp: 17.85,
            minScreenAirTemp: 17.61,
            screenDewPointTemperature: 14.08,
            feelsLikeTemperature: 16.47,
            windSpeed10m: 4.31,
            windDirectionFrom10m: 226,
            windGustSpeed10m: 8.42,
            max10mWindGust: 8.44,
            visibility: 18878,
            screenRelativeHumidity: 79.07,
            mslp: 101078,
            uvIndex: 3,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 20,
          },
          {
            time: '2023-07-11T10:00Z',
            screenTemperature: 18.5,
            maxScreenAirTemp: 18.54,
            minScreenAirTemp: 17.81,
            screenDewPointTemperature: 13.46,
            feelsLikeTemperature: 16.94,
            windSpeed10m: 4.49,
            windDirectionFrom10m: 226,
            windGustSpeed10m: 8.77,
            max10mWindGust: 8.77,
            visibility: 21027,
            screenRelativeHumidity: 72.94,
            mslp: 101064,
            uvIndex: 4,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 9,
          },
          {
            time: '2023-07-11T11:00Z',
            screenTemperature: 19.37,
            maxScreenAirTemp: 19.4,
            minScreenAirTemp: 18.5,
            screenDewPointTemperature: 12.94,
            feelsLikeTemperature: 17.4,
            windSpeed10m: 4.93,
            windDirectionFrom10m: 230,
            windGustSpeed10m: 9.68,
            max10mWindGust: 9.68,
            visibility: 22034,
            screenRelativeHumidity: 66.9,
            mslp: 101050,
            uvIndex: 5,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 11,
          },
          {
            time: '2023-07-11T12:00Z',
            screenTemperature: 20.15,
            maxScreenAirTemp: 20.2,
            minScreenAirTemp: 19.37,
            screenDewPointTemperature: 12.5,
            feelsLikeTemperature: 17.83,
            windSpeed10m: 5.26,
            windDirectionFrom10m: 230,
            windGustSpeed10m: 10.32,
            max10mWindGust: 10.32,
            visibility: 23885,
            screenRelativeHumidity: 62.0,
            mslp: 101030,
            uvIndex: 6,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 10,
          },
          {
            time: '2023-07-11T13:00Z',
            screenTemperature: 20.62,
            maxScreenAirTemp: 20.71,
            minScreenAirTemp: 20.15,
            screenDewPointTemperature: 12.12,
            feelsLikeTemperature: 17.93,
            windSpeed10m: 5.67,
            windDirectionFrom10m: 232,
            windGustSpeed10m: 11.12,
            max10mWindGust: 11.12,
            visibility: 24590,
            screenRelativeHumidity: 58.72,
            mslp: 101006,
            uvIndex: 5,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 12,
          },
          {
            time: '2023-07-11T14:00Z',
            screenTemperature: 21.08,
            maxScreenAirTemp: 21.15,
            minScreenAirTemp: 20.62,
            screenDewPointTemperature: 11.63,
            feelsLikeTemperature: 18.26,
            windSpeed10m: 5.72,
            windDirectionFrom10m: 233,
            windGustSpeed10m: 11.23,
            max10mWindGust: 11.23,
            visibility: 28009,
            screenRelativeHumidity: 55.21,
            mslp: 100952,
            uvIndex: 4,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 8,
          },
          {
            time: '2023-07-11T15:00Z',
            screenTemperature: 20.82,
            maxScreenAirTemp: 21.08,
            minScreenAirTemp: 20.77,
            screenDewPointTemperature: 11.63,
            feelsLikeTemperature: 17.64,
            windSpeed10m: 6.29,
            windDirectionFrom10m: 230,
            windGustSpeed10m: 12.36,
            max10mWindGust: 12.36,
            visibility: 24025,
            screenRelativeHumidity: 56.11,
            mslp: 100920,
            uvIndex: 3,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 12,
          },
          {
            time: '2023-07-11T16:00Z',
            screenTemperature: 20.29,
            maxScreenAirTemp: 20.82,
            minScreenAirTemp: 20.26,
            screenDewPointTemperature: 11.65,
            feelsLikeTemperature: 17.2,
            windSpeed10m: 6.22,
            windDirectionFrom10m: 230,
            windGustSpeed10m: 12.22,
            max10mWindGust: 12.4,
            visibility: 29357,
            screenRelativeHumidity: 57.97,
            mslp: 100892,
            uvIndex: 2,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 6,
          },
          {
            time: '2023-07-11T17:00Z',
            screenTemperature: 19.98,
            maxScreenAirTemp: 20.29,
            minScreenAirTemp: 19.85,
            screenDewPointTemperature: 11.73,
            feelsLikeTemperature: 17.03,
            windSpeed10m: 6.05,
            windDirectionFrom10m: 227,
            windGustSpeed10m: 11.79,
            max10mWindGust: 12.1,
            visibility: 28094,
            screenRelativeHumidity: 59.27,
            mslp: 100856,
            uvIndex: 2,
            significantWeatherCode: 3,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 1,
          },
          {
            time: '2023-07-11T18:00Z',
            screenTemperature: 19.73,
            maxScreenAirTemp: 19.98,
            minScreenAirTemp: 19.67,
            screenDewPointTemperature: 11.86,
            feelsLikeTemperature: 16.72,
            windSpeed10m: 6.18,
            windDirectionFrom10m: 228,
            windGustSpeed10m: 12.15,
            max10mWindGust: 12.44,
            visibility: 28180,
            screenRelativeHumidity: 60.59,
            mslp: 100828,
            uvIndex: 1,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 4,
          },
          {
            time: '2023-07-11T19:00Z',
            screenTemperature: 19.18,
            maxScreenAirTemp: 19.73,
            minScreenAirTemp: 19.14,
            screenDewPointTemperature: 12.3,
            feelsLikeTemperature: 16.42,
            windSpeed10m: 6.03,
            windDirectionFrom10m: 229,
            windGustSpeed10m: 11.86,
            max10mWindGust: 12.09,
            visibility: 27518,
            screenRelativeHumidity: 64.68,
            mslp: 100830,
            uvIndex: 1,
            significantWeatherCode: 3,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 1,
          },
          {
            time: '2023-07-11T20:00Z',
            screenTemperature: 18.52,
            maxScreenAirTemp: 19.18,
            minScreenAirTemp: 18.5,
            screenDewPointTemperature: 12.63,
            feelsLikeTemperature: 16.14,
            windSpeed10m: 5.65,
            windDirectionFrom10m: 230,
            windGustSpeed10m: 11.19,
            max10mWindGust: 11.89,
            visibility: 24496,
            screenRelativeHumidity: 68.8,
            mslp: 100848,
            uvIndex: 1,
            significantWeatherCode: 3,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 3,
          },
          {
            time: '2023-07-11T21:00Z',
            screenTemperature: 18.0,
            maxScreenAirTemp: 18.52,
            minScreenAirTemp: 17.97,
            screenDewPointTemperature: 12.9,
            feelsLikeTemperature: 15.9,
            windSpeed10m: 5.38,
            windDirectionFrom10m: 231,
            windGustSpeed10m: 10.65,
            max10mWindGust: 11.31,
            visibility: 23856,
            screenRelativeHumidity: 72.28,
            mslp: 100866,
            uvIndex: 0,
            significantWeatherCode: 2,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 2,
          },
          {
            time: '2023-07-11T22:00Z',
            screenTemperature: 17.48,
            maxScreenAirTemp: 18.0,
            minScreenAirTemp: 17.46,
            screenDewPointTemperature: 13.06,
            feelsLikeTemperature: 15.62,
            windSpeed10m: 5.05,
            windDirectionFrom10m: 236,
            windGustSpeed10m: 10.02,
            max10mWindGust: 10.91,
            visibility: 24317,
            screenRelativeHumidity: 75.58,
            mslp: 100882,
            uvIndex: 0,
            significantWeatherCode: 2,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 1,
          },
          {
            time: '2023-07-11T23:00Z',
            screenTemperature: 16.95,
            maxScreenAirTemp: 17.48,
            minScreenAirTemp: 16.93,
            screenDewPointTemperature: 13.06,
            feelsLikeTemperature: 15.38,
            windSpeed10m: 4.58,
            windDirectionFrom10m: 242,
            windGustSpeed10m: 9.25,
            max10mWindGust: 9.96,
            visibility: 25193,
            screenRelativeHumidity: 78.01,
            mslp: 100906,
            uvIndex: 0,
            significantWeatherCode: 0,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 3,
          },
          {
            time: '2023-07-12T00:00Z',
            screenTemperature: 16.4,
            maxScreenAirTemp: 16.95,
            minScreenAirTemp: 16.38,
            screenDewPointTemperature: 12.93,
            feelsLikeTemperature: 14.91,
            windSpeed10m: 4.42,
            windDirectionFrom10m: 247,
            windGustSpeed10m: 8.78,
            max10mWindGust: 9.23,
            visibility: 25835,
            screenRelativeHumidity: 80.04,
            mslp: 100938,
            uvIndex: 0,
            significantWeatherCode: 2,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 3,
          },
          {
            time: '2023-07-12T01:00Z',
            screenTemperature: 15.86,
            maxScreenAirTemp: 16.4,
            minScreenAirTemp: 15.84,
            screenDewPointTemperature: 12.62,
            feelsLikeTemperature: 14.46,
            windSpeed10m: 4.21,
            windDirectionFrom10m: 249,
            windGustSpeed10m: 8.34,
            max10mWindGust: 8.62,
            visibility: 25407,
            screenRelativeHumidity: 81.19,
            mslp: 100966,
            uvIndex: 0,
            significantWeatherCode: 2,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 3,
          },
          {
            time: '2023-07-12T02:00Z',
            screenTemperature: 15.45,
            maxScreenAirTemp: 15.86,
            minScreenAirTemp: 15.44,
            screenDewPointTemperature: 12.47,
            feelsLikeTemperature: 14.15,
            windSpeed10m: 3.94,
            windDirectionFrom10m: 250,
            windGustSpeed10m: 7.76,
            max10mWindGust: 8.02,
            visibility: 24489,
            screenRelativeHumidity: 82.6,
            mslp: 100984,
            uvIndex: 0,
            significantWeatherCode: 2,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2023-07-12T03:00Z',
            screenTemperature: 15.03,
            maxScreenAirTemp: 15.45,
            minScreenAirTemp: 15.02,
            screenDewPointTemperature: 12.23,
            feelsLikeTemperature: 13.78,
            windSpeed10m: 3.79,
            windDirectionFrom10m: 249,
            windGustSpeed10m: 7.46,
            max10mWindGust: 7.46,
            visibility: 23281,
            screenRelativeHumidity: 83.42,
            mslp: 101004,
            uvIndex: 0,
            significantWeatherCode: 2,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2023-07-12T04:00Z',
            screenTemperature: 14.88,
            maxScreenAirTemp: 15.03,
            minScreenAirTemp: 14.88,
            screenDewPointTemperature: 12.16,
            feelsLikeTemperature: 13.58,
            windSpeed10m: 3.87,
            windDirectionFrom10m: 245,
            windGustSpeed10m: 7.7,
            max10mWindGust: 7.7,
            visibility: 21424,
            screenRelativeHumidity: 83.92,
            mslp: 101046,
            uvIndex: 0,
            significantWeatherCode: 2,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2023-07-12T05:00Z',
            screenTemperature: 14.84,
            maxScreenAirTemp: 14.88,
            minScreenAirTemp: 14.83,
            screenDewPointTemperature: 12.01,
            feelsLikeTemperature: 13.45,
            windSpeed10m: 4.04,
            windDirectionFrom10m: 245,
            windGustSpeed10m: 7.84,
            max10mWindGust: 7.84,
            visibility: 20716,
            screenRelativeHumidity: 83.3,
            mslp: 101088,
            uvIndex: 1,
            significantWeatherCode: 3,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2023-07-12T06:00Z',
            screenTemperature: 15.02,
            maxScreenAirTemp: 15.13,
            minScreenAirTemp: 14.84,
            screenDewPointTemperature: 11.96,
            feelsLikeTemperature: 13.59,
            windSpeed10m: 4.09,
            windDirectionFrom10m: 244,
            windGustSpeed10m: 7.87,
            max10mWindGust: 7.87,
            visibility: 20387,
            screenRelativeHumidity: 82.11,
            mslp: 101138,
            uvIndex: 1,
            significantWeatherCode: 3,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2023-07-12T07:00Z',
            screenTemperature: 15.99,
            maxScreenAirTemp: 16.0,
            minScreenAirTemp: 15.02,
            screenDewPointTemperature: 11.83,
            feelsLikeTemperature: 14.47,
            windSpeed10m: 4.19,
            windDirectionFrom10m: 244,
            windGustSpeed10m: 8.15,
            max10mWindGust: 8.15,
            visibility: 20619,
            screenRelativeHumidity: 76.77,
            mslp: 101160,
            uvIndex: 3,
            significantWeatherCode: 3,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2023-07-12T08:00Z',
            screenTemperature: 17.21,
            maxScreenAirTemp: 17.24,
            minScreenAirTemp: 15.99,
            screenDewPointTemperature: 11.45,
            feelsLikeTemperature: 15.43,
            windSpeed10m: 4.47,
            windDirectionFrom10m: 245,
            windGustSpeed10m: 9.0,
            max10mWindGust: 9.0,
            visibility: 20206,
            screenRelativeHumidity: 69.42,
            mslp: 101190,
            uvIndex: 4,
            significantWeatherCode: 1,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 3,
          },
          {
            time: '2023-07-12T09:00Z',
            screenTemperature: 18.31,
            maxScreenAirTemp: 18.45,
            minScreenAirTemp: 17.21,
            screenDewPointTemperature: 10.43,
            feelsLikeTemperature: 15.95,
            windSpeed10m: 5.05,
            windDirectionFrom10m: 249,
            windGustSpeed10m: 10.07,
            max10mWindGust: 10.07,
            visibility: 23551,
            screenRelativeHumidity: 60.56,
            mslp: 101204,
            uvIndex: 5,
            significantWeatherCode: 3,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 4,
          },
          {
            time: '2023-07-12T10:00Z',
            screenTemperature: 18.9,
            maxScreenAirTemp: 19.15,
            minScreenAirTemp: 18.31,
            screenDewPointTemperature: 10.45,
            feelsLikeTemperature: 16.52,
            windSpeed10m: 4.94,
            windDirectionFrom10m: 248,
            windGustSpeed10m: 10.24,
            max10mWindGust: 10.24,
            visibility: 22531,
            screenRelativeHumidity: 58.58,
            mslp: 101212,
            uvIndex: 5,
            significantWeatherCode: 3,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 6,
          },
          {
            time: '2023-07-12T11:00Z',
            screenTemperature: 19.64,
            maxScreenAirTemp: 19.93,
            minScreenAirTemp: 18.83,
            screenDewPointTemperature: 10.05,
            feelsLikeTemperature: 16.69,
            windSpeed10m: 5.58,
            windDirectionFrom10m: 247,
            windGustSpeed10m: 11.38,
            max10mWindGust: 11.38,
            visibility: 24695,
            screenRelativeHumidity: 54.54,
            mslp: 101204,
            uvIndex: 5,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 16,
          },
          {
            time: '2023-07-12T12:00Z',
            screenTemperature: 20.32,
            maxScreenAirTemp: 20.5,
            minScreenAirTemp: 19.64,
            screenDewPointTemperature: 9.44,
            feelsLikeTemperature: 16.92,
            windSpeed10m: 6.04,
            windDirectionFrom10m: 247,
            windGustSpeed10m: 12.24,
            max10mWindGust: 12.24,
            visibility: 25217,
            screenRelativeHumidity: 49.83,
            mslp: 101194,
            uvIndex: 6,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 9,
          },
          {
            time: '2023-07-12T13:00Z',
            screenTemperature: 20.46,
            maxScreenAirTemp: 20.48,
            minScreenAirTemp: 20.32,
            screenDewPointTemperature: 10.11,
            feelsLikeTemperature: 17.26,
            windSpeed10m: 5.89,
            windDirectionFrom10m: 242,
            windGustSpeed10m: 12.13,
            max10mWindGust: 12.13,
            visibility: 24824,
            screenRelativeHumidity: 51.94,
            mslp: 101186,
            uvIndex: 5,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 12,
          },
          {
            time: '2023-07-12T14:00Z',
            screenTemperature: 20.36,
            maxScreenAirTemp: 20.46,
            minScreenAirTemp: 20.2,
            screenDewPointTemperature: 10.98,
            feelsLikeTemperature: 17.11,
            windSpeed10m: 6.22,
            windDirectionFrom10m: 239,
            windGustSpeed10m: 12.66,
            max10mWindGust: 12.66,
            visibility: 24796,
            screenRelativeHumidity: 55.33,
            mslp: 101196,
            uvIndex: 4,
            significantWeatherCode: 10,
            precipitationRate: 0.77,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 34,
          },
          {
            time: '2023-07-12T15:00Z',
            screenTemperature: 20.48,
            screenDewPointTemperature: 11.5,
            feelsLikeTemperature: 17.33,
            windSpeed10m: 6.23,
            windDirectionFrom10m: 236,
            windGustSpeed10m: 12.75,
            visibility: 24696,
            screenRelativeHumidity: 57.01,
            mslp: 101180,
            uvIndex: 3,
            significantWeatherCode: 10,
            precipitationRate: 0.76,
            probOfPrecipitation: 35,
          },
          {
            time: '2023-07-12T16:00Z',
            screenTemperature: 20.18,
            screenDewPointTemperature: 11.71,
            feelsLikeTemperature: 17.21,
            windSpeed10m: 6.03,
            windDirectionFrom10m: 238,
            windGustSpeed10m: 12.56,
            visibility: 23778,
            screenRelativeHumidity: 58.83,
            mslp: 101196,
            uvIndex: 2,
            significantWeatherCode: 10,
            precipitationRate: 0.75,
            probOfPrecipitation: 35,
          },
          {
            time: '2023-07-12T17:00Z',
            screenTemperature: 19.96,
            screenDewPointTemperature: 11.72,
            feelsLikeTemperature: 17.17,
            windSpeed10m: 5.78,
            windDirectionFrom10m: 236,
            windGustSpeed10m: 11.99,
            visibility: 24512,
            screenRelativeHumidity: 59.65,
            mslp: 101198,
            uvIndex: 2,
            significantWeatherCode: 10,
            precipitationRate: 0.52,
            probOfPrecipitation: 36,
          },
        ],
      },
    },
  ],
  parameters: [
    {
      totalSnowAmount: {
        type: 'Parameter',
        description: 'Total Snow Amount Over Previous Hour',
        unit: {
          label: 'millimetres',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'mm',
          },
        },
      },
      screenTemperature: {
        type: 'Parameter',
        description: 'Screen Air Temperature',
        unit: {
          label: 'degrees Celsius',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'Cel',
          },
        },
      },
      visibility: {
        type: 'Parameter',
        description: 'Visibility',
        unit: {
          label: 'metres',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'm',
          },
        },
      },
      windDirectionFrom10m: {
        type: 'Parameter',
        description: '10m Wind From Direction',
        unit: {
          label: 'degrees',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'deg',
          },
        },
      },
      precipitationRate: {
        type: 'Parameter',
        description: 'Precipitation Rate',
        unit: {
          label: 'millimetres per hour',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'mm/h',
          },
        },
      },
      maxScreenAirTemp: {
        type: 'Parameter',
        description: 'Maximum Screen Air Temperature Over Previous Hour',
        unit: {
          label: 'degrees Celsius',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'Cel',
          },
        },
      },
      feelsLikeTemperature: {
        type: 'Parameter',
        description: 'Feels Like Temperature',
        unit: {
          label: 'degrees Celsius',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'Cel',
          },
        },
      },
      screenDewPointTemperature: {
        type: 'Parameter',
        description: 'Screen Dew Point Temperature',
        unit: {
          label: 'degrees Celsius',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'Cel',
          },
        },
      },
      screenRelativeHumidity: {
        type: 'Parameter',
        description: 'Screen Relative Humidity',
        unit: {
          label: 'percentage',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: '%',
          },
        },
      },
      windSpeed10m: {
        type: 'Parameter',
        description: '10m Wind Speed',
        unit: {
          label: 'metres per second',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'm/s',
          },
        },
      },
      probOfPrecipitation: {
        type: 'Parameter',
        description: 'Probability of Precipitation',
        unit: {
          label: 'percentage',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: '%',
          },
        },
      },
      max10mWindGust: {
        type: 'Parameter',
        description: 'Maximum 10m Wind Gust Speed Over Previous Hour',
        unit: {
          label: 'metres per second',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'm/s',
          },
        },
      },
      significantWeatherCode: {
        type: 'Parameter',
        description: 'Significant Weather Code',
        unit: {
          label: 'dimensionless',
          symbol: {
            value:
              'https://metoffice.apiconnect.ibmcloud.com/metoffice/production/',
            type: '1',
          },
        },
      },
      minScreenAirTemp: {
        type: 'Parameter',
        description: 'Minimum Screen Air Temperature Over Previous Hour',
        unit: {
          label: 'degrees Celsius',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'Cel',
          },
        },
      },
      totalPrecipAmount: {
        type: 'Parameter',
        description: 'Total Precipitation Amount Over Previous Hour',
        unit: {
          label: 'millimetres',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'mm',
          },
        },
      },
      mslp: {
        type: 'Parameter',
        description: 'Mean Sea Level Pressure',
        unit: {
          label: 'pascals',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'Pa',
          },
        },
      },
      windGustSpeed10m: {
        type: 'Parameter',
        description: '10m Wind Gust Speed',
        unit: {
          label: 'metres per second',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'm/s',
          },
        },
      },
      uvIndex: {
        type: 'Parameter',
        description: 'UV Index',
        unit: {
          label: 'dimensionless',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: '1',
          },
        },
      },
    },
  ],
};

const getMockHourlyMetOfficeJSON = () => mockHourlyMetOfficeJSON;

export default getMockHourlyMetOfficeJSON;
