const stormTestHourlyForecast = {
  type: 'FeatureCollection',
  features: [
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [0.042, 51.4862, 31.0],
      },
      properties: {
        requestPointDistance: 1029.857,
        modelRunDate: '2025-08-04T12:00Z',
        timeSeries: [
          {
            time: '2025-08-04T12:00Z',
            screenTemperature: 21.16,
            maxScreenAirTemp: 21.16,
            minScreenAirTemp: 20.96,
            screenDewPointTemperature: 17.47,
            feelsLikeTemperature: 18.44,
            windSpeed10m: 7.46,
            windDirectionFrom10m: 228,
            windGustSpeed10m: 12.86,
            max10mWindGust: 15.41,
            visibility: 7986,
            screenRelativeHumidity: 79.22,
            mslp: 101360,
            uvIndex: 4,
            significantWeatherCode: 12,
            precipitationRate: 0.44,
            totalPrecipAmount: 0.16,
            totalSnowAmount: 0,
            probOfPrecipitation: 62,
          },
          {
            time: '2025-08-04T13:00Z',
            screenTemperature: 20.83,
            maxScreenAirTemp: 21.16,
            minScreenAirTemp: 20.78,
            screenDewPointTemperature: 17.33,
            feelsLikeTemperature: 17.28,
            windSpeed10m: 8.66,
            windDirectionFrom10m: 225,
            windGustSpeed10m: 14.3,
            max10mWindGust: 15.61,
            visibility: 8722,
            screenRelativeHumidity: 80.15,
            mslp: 101332,
            uvIndex: 3,
            significantWeatherCode: 7,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 5,
          },
          {
            time: '2025-08-04T14:00Z',
            screenTemperature: 20.75,
            maxScreenAirTemp: 20.86,
            minScreenAirTemp: 20.73,
            screenDewPointTemperature: 16.96,
            feelsLikeTemperature: 17.39,
            windSpeed10m: 8.21,
            windDirectionFrom10m: 225,
            windGustSpeed10m: 14.11,
            max10mWindGust: 15.64,
            visibility: 9306,
            screenRelativeHumidity: 78.72,
            mslp: 101306,
            uvIndex: 3,
            significantWeatherCode: 10,
            precipitationRate: 0.34,
            totalPrecipAmount: 0.05,
            totalSnowAmount: 0,
            probOfPrecipitation: 32,
          },
          {
            time: '2025-08-04T15:00Z',
            screenTemperature: 20.66,
            maxScreenAirTemp: 20.9,
            minScreenAirTemp: 20.65,
            screenDewPointTemperature: 17.34,
            feelsLikeTemperature: 17.7,
            windSpeed10m: 7.75,
            windDirectionFrom10m: 236,
            windGustSpeed10m: 13.7,
            max10mWindGust: 15.14,
            visibility: 6036,
            screenRelativeHumidity: 81.1,
            mslp: 101279,
            uvIndex: 2,
            significantWeatherCode: 14,
            precipitationRate: 2.05,
            totalPrecipAmount: 0.33,
            totalSnowAmount: 0,
            probOfPrecipitation: 75,
          },
          {
            time: '2025-08-04T16:00Z',
            screenTemperature: 19.86,
            maxScreenAirTemp: 20.66,
            minScreenAirTemp: 19.85,
            screenDewPointTemperature: 18.05,
            feelsLikeTemperature: 17.69,
            windSpeed10m: 6.83,
            windDirectionFrom10m: 234,
            windGustSpeed10m: 12.19,
            max10mWindGust: 13.37,
            visibility: 6429,
            screenRelativeHumidity: 89.36,
            mslp: 101300,
            uvIndex: 2,
            significantWeatherCode: 15,
            precipitationRate: 1.39,
            totalPrecipAmount: 0.82,
            totalSnowAmount: 0,
            probOfPrecipitation: 95,
          },
          {
            time: '2025-08-04T17:00Z',
            screenTemperature: 19.7,
            maxScreenAirTemp: 19.86,
            minScreenAirTemp: 19.66,
            screenDewPointTemperature: 17.9,
            feelsLikeTemperature: 18.02,
            windSpeed10m: 6.04,
            windDirectionFrom10m: 244,
            windGustSpeed10m: 11.14,
            max10mWindGust: 12.05,
            visibility: 14242,
            screenRelativeHumidity: 89.37,
            mslp: 101320,
            uvIndex: 1,
            significantWeatherCode: 12,
            precipitationRate: 0.18,
            totalPrecipAmount: 0.21,
            totalSnowAmount: 0,
            probOfPrecipitation: 48,
          },
          {
            time: '2025-08-04T18:00Z',
            screenTemperature: 20.18,
            maxScreenAirTemp: 20.19,
            minScreenAirTemp: 19.7,
            screenDewPointTemperature: 16.95,
            feelsLikeTemperature: 19.1,
            windSpeed10m: 4.68,
            windDirectionFrom10m: 258,
            windGustSpeed10m: 8.61,
            max10mWindGust: 10.6,
            visibility: 15708,
            screenRelativeHumidity: 81.65,
            mslp: 101360,
            uvIndex: 1,
            significantWeatherCode: 1,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 6,
          },
          {
            time: '2025-08-04T19:00Z',
            screenTemperature: 20.13,
            maxScreenAirTemp: 20.26,
            minScreenAirTemp: 20.13,
            screenDewPointTemperature: 14.93,
            feelsLikeTemperature: 19.25,
            windSpeed10m: 3.67,
            windDirectionFrom10m: 241,
            windGustSpeed10m: 8.12,
            max10mWindGust: 8.27,
            visibility: 16931,
            screenRelativeHumidity: 71.88,
            mslp: 101420,
            uvIndex: 1,
            significantWeatherCode: 1,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 1,
          },
          {
            time: '2025-08-04T20:00Z',
            screenTemperature: 20.01,
            maxScreenAirTemp: 20.13,
            minScreenAirTemp: 19.98,
            screenDewPointTemperature: 11.1,
            feelsLikeTemperature: 18.12,
            windSpeed10m: 4.15,
            windDirectionFrom10m: 265,
            windGustSpeed10m: 9.39,
            max10mWindGust: 9.56,
            visibility: 20078,
            screenRelativeHumidity: 57.41,
            mslp: 101524,
            uvIndex: 0,
            significantWeatherCode: 0,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-04T21:00Z',
            screenTemperature: 19.4,
            maxScreenAirTemp: 20.01,
            minScreenAirTemp: 19.39,
            screenDewPointTemperature: 8.25,
            feelsLikeTemperature: 17.21,
            windSpeed10m: 3.98,
            windDirectionFrom10m: 288,
            windGustSpeed10m: 9.29,
            max10mWindGust: 9.76,
            visibility: 27858,
            screenRelativeHumidity: 48.76,
            mslp: 101614,
            uvIndex: 0,
            significantWeatherCode: 0,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-04T22:00Z',
            screenTemperature: 18.45,
            maxScreenAirTemp: 19.4,
            minScreenAirTemp: 18.44,
            screenDewPointTemperature: 7.15,
            feelsLikeTemperature: 16.26,
            windSpeed10m: 4.07,
            windDirectionFrom10m: 298,
            windGustSpeed10m: 8.96,
            max10mWindGust: 9.44,
            visibility: 33504,
            screenRelativeHumidity: 47.94,
            mslp: 101684,
            uvIndex: 0,
            significantWeatherCode: 0,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 1,
          },
          {
            time: '2025-08-04T23:00Z',
            screenTemperature: 17.6,
            maxScreenAirTemp: 18.34,
            minScreenAirTemp: 17.59,
            screenDewPointTemperature: 7.56,
            feelsLikeTemperature: 15.75,
            windSpeed10m: 3.76,
            windDirectionFrom10m: 286,
            windGustSpeed10m: 8.29,
            max10mWindGust: 9.48,
            visibility: 35063,
            screenRelativeHumidity: 52.07,
            mslp: 101721,
            uvIndex: 0,
            significantWeatherCode: 0,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-05T00:00Z',
            screenTemperature: 16.91,
            maxScreenAirTemp: 17.6,
            minScreenAirTemp: 16.9,
            screenDewPointTemperature: 7.57,
            feelsLikeTemperature: 15.29,
            windSpeed10m: 3.49,
            windDirectionFrom10m: 279,
            windGustSpeed10m: 7.41,
            max10mWindGust: 8.33,
            visibility: 34119,
            screenRelativeHumidity: 54.34,
            mslp: 101741,
            uvIndex: 0,
            significantWeatherCode: 2,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-05T01:00Z',
            screenTemperature: 16.24,
            maxScreenAirTemp: 16.91,
            minScreenAirTemp: 16.24,
            screenDewPointTemperature: 7.81,
            feelsLikeTemperature: 14.8,
            windSpeed10m: 3.29,
            windDirectionFrom10m: 270,
            windGustSpeed10m: 6.94,
            max10mWindGust: 7.84,
            visibility: 30115,
            screenRelativeHumidity: 57.57,
            mslp: 101771,
            uvIndex: 0,
            significantWeatherCode: 0,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-05T02:00Z',
            screenTemperature: 15.62,
            maxScreenAirTemp: 16.24,
            minScreenAirTemp: 15.61,
            screenDewPointTemperature: 8.17,
            feelsLikeTemperature: 14.24,
            windSpeed10m: 3.31,
            windDirectionFrom10m: 268,
            windGustSpeed10m: 7.2,
            max10mWindGust: 7.6,
            visibility: 27414,
            screenRelativeHumidity: 61.34,
            mslp: 101784,
            uvIndex: 0,
            significantWeatherCode: 0,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-05T03:00Z',
            screenTemperature: 14.99,
            maxScreenAirTemp: 15.62,
            minScreenAirTemp: 14.98,
            screenDewPointTemperature: 8.49,
            feelsLikeTemperature: 13.39,
            windSpeed10m: 3.85,
            windDirectionFrom10m: 267,
            windGustSpeed10m: 7.89,
            max10mWindGust: 8.2,
            visibility: 26353,
            screenRelativeHumidity: 65.21,
            mslp: 101830,
            uvIndex: 0,
            significantWeatherCode: 0,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-05T04:00Z',
            screenTemperature: 14.55,
            maxScreenAirTemp: 14.99,
            minScreenAirTemp: 14.54,
            screenDewPointTemperature: 8.2,
            feelsLikeTemperature: 12.75,
            windSpeed10m: 4.25,
            windDirectionFrom10m: 269,
            windGustSpeed10m: 8.34,
            max10mWindGust: 8.83,
            visibility: 27949,
            screenRelativeHumidity: 65.74,
            mslp: 101887,
            uvIndex: 0,
            significantWeatherCode: 0,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-05T05:00Z',
            screenTemperature: 14.13,
            maxScreenAirTemp: 14.55,
            minScreenAirTemp: 14.11,
            screenDewPointTemperature: 8.25,
            feelsLikeTemperature: 12.36,
            windSpeed10m: 4.2,
            windDirectionFrom10m: 266,
            windGustSpeed10m: 8.25,
            max10mWindGust: 8.59,
            visibility: 25154,
            screenRelativeHumidity: 67.8,
            mslp: 101947,
            uvIndex: 1,
            significantWeatherCode: 1,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-05T06:00Z',
            screenTemperature: 13.99,
            maxScreenAirTemp: 14.13,
            minScreenAirTemp: 13.91,
            screenDewPointTemperature: 8.13,
            feelsLikeTemperature: 11.94,
            windSpeed10m: 4.83,
            windDirectionFrom10m: 267,
            windGustSpeed10m: 8.6,
            max10mWindGust: 9.04,
            visibility: 24982,
            screenRelativeHumidity: 67.84,
            mslp: 102027,
            uvIndex: 1,
            significantWeatherCode: 1,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-05T07:00Z',
            screenTemperature: 14.59,
            maxScreenAirTemp: 14.59,
            minScreenAirTemp: 13.99,
            screenDewPointTemperature: 8.1,
            feelsLikeTemperature: 12.29,
            windSpeed10m: 5.3,
            windDirectionFrom10m: 271,
            windGustSpeed10m: 9.24,
            max10mWindGust: 9.53,
            visibility: 25626,
            screenRelativeHumidity: 65.19,
            mslp: 102077,
            uvIndex: 2,
            significantWeatherCode: 1,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-05T08:00Z',
            screenTemperature: 15.67,
            maxScreenAirTemp: 15.69,
            minScreenAirTemp: 14.59,
            screenDewPointTemperature: 8.03,
            feelsLikeTemperature: 13.1,
            windSpeed10m: 5.71,
            windDirectionFrom10m: 278,
            windGustSpeed10m: 10.1,
            max10mWindGust: 10.1,
            visibility: 29498,
            screenRelativeHumidity: 60.51,
            mslp: 102133,
            uvIndex: 3,
            significantWeatherCode: 1,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-05T09:00Z',
            screenTemperature: 17.07,
            maxScreenAirTemp: 17.08,
            minScreenAirTemp: 15.67,
            screenDewPointTemperature: 7.0,
            feelsLikeTemperature: 14.06,
            windSpeed10m: 5.99,
            windDirectionFrom10m: 285,
            windGustSpeed10m: 10.89,
            max10mWindGust: 10.89,
            visibility: 33686,
            screenRelativeHumidity: 51.61,
            mslp: 102160,
            uvIndex: 4,
            significantWeatherCode: 1,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-05T10:00Z',
            screenTemperature: 18.15,
            maxScreenAirTemp: 18.16,
            minScreenAirTemp: 17.07,
            screenDewPointTemperature: 6.54,
            feelsLikeTemperature: 14.95,
            windSpeed10m: 5.78,
            windDirectionFrom10m: 283,
            windGustSpeed10m: 10.53,
            max10mWindGust: 10.99,
            visibility: 35014,
            screenRelativeHumidity: 46.89,
            mslp: 102186,
            uvIndex: 5,
            significantWeatherCode: 3,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-05T11:00Z',
            screenTemperature: 19.13,
            maxScreenAirTemp: 19.14,
            minScreenAirTemp: 18.15,
            screenDewPointTemperature: 5.77,
            feelsLikeTemperature: 15.52,
            windSpeed10m: 5.88,
            windDirectionFrom10m: 285,
            windGustSpeed10m: 10.69,
            max10mWindGust: 11.33,
            visibility: 36683,
            screenRelativeHumidity: 41.91,
            mslp: 102206,
            uvIndex: 6,
            significantWeatherCode: 3,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-05T12:00Z',
            screenTemperature: 20.3,
            maxScreenAirTemp: 20.32,
            minScreenAirTemp: 19.13,
            screenDewPointTemperature: 4.87,
            feelsLikeTemperature: 16.14,
            windSpeed10m: 6.18,
            windDirectionFrom10m: 289,
            windGustSpeed10m: 11.44,
            max10mWindGust: 11.44,
            visibility: 36280,
            screenRelativeHumidity: 36.54,
            mslp: 102222,
            uvIndex: 6,
            significantWeatherCode: 3,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-05T13:00Z',
            screenTemperature: 21.06,
            maxScreenAirTemp: 21.07,
            minScreenAirTemp: 20.3,
            screenDewPointTemperature: 4.34,
            feelsLikeTemperature: 16.96,
            windSpeed10m: 6.05,
            windDirectionFrom10m: 287,
            windGustSpeed10m: 11.08,
            max10mWindGust: 11.2,
            visibility: 37558,
            screenRelativeHumidity: 33.78,
            mslp: 102242,
            uvIndex: 5,
            significantWeatherCode: 3,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-05T14:00Z',
            screenTemperature: 21.67,
            maxScreenAirTemp: 21.72,
            minScreenAirTemp: 21.06,
            screenDewPointTemperature: 4.53,
            feelsLikeTemperature: 17.5,
            windSpeed10m: 6.21,
            windDirectionFrom10m: 292,
            windGustSpeed10m: 11.49,
            max10mWindGust: 11.56,
            visibility: 37115,
            screenRelativeHumidity: 32.99,
            mslp: 102269,
            uvIndex: 4,
            significantWeatherCode: 1,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-05T15:00Z',
            screenTemperature: 22.11,
            maxScreenAirTemp: 22.16,
            minScreenAirTemp: 21.67,
            screenDewPointTemperature: 4.17,
            feelsLikeTemperature: 17.94,
            windSpeed10m: 6.18,
            windDirectionFrom10m: 293,
            windGustSpeed10m: 11.47,
            max10mWindGust: 11.75,
            visibility: 37682,
            screenRelativeHumidity: 31.28,
            mslp: 102286,
            uvIndex: 3,
            significantWeatherCode: 1,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-05T16:00Z',
            screenTemperature: 22.12,
            maxScreenAirTemp: 22.17,
            minScreenAirTemp: 22.11,
            screenDewPointTemperature: 4.66,
            feelsLikeTemperature: 18.01,
            windSpeed10m: 6.16,
            windDirectionFrom10m: 293,
            windGustSpeed10m: 11.51,
            max10mWindGust: 11.62,
            visibility: 38134,
            screenRelativeHumidity: 32.38,
            mslp: 102310,
            uvIndex: 3,
            significantWeatherCode: 1,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-05T17:00Z',
            screenTemperature: 21.85,
            maxScreenAirTemp: 22.12,
            minScreenAirTemp: 21.84,
            screenDewPointTemperature: 4.64,
            feelsLikeTemperature: 17.96,
            windSpeed10m: 5.82,
            windDirectionFrom10m: 299,
            windGustSpeed10m: 10.89,
            max10mWindGust: 11.88,
            visibility: 38239,
            screenRelativeHumidity: 32.97,
            mslp: 102336,
            uvIndex: 2,
            significantWeatherCode: 3,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-05T18:00Z',
            screenTemperature: 21.41,
            maxScreenAirTemp: 21.85,
            minScreenAirTemp: 21.4,
            screenDewPointTemperature: 4.84,
            feelsLikeTemperature: 17.65,
            windSpeed10m: 5.63,
            windDirectionFrom10m: 301,
            windGustSpeed10m: 10.47,
            max10mWindGust: 11.06,
            visibility: 39395,
            screenRelativeHumidity: 34.34,
            mslp: 102376,
            uvIndex: 1,
            significantWeatherCode: 1,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-05T19:00Z',
            screenTemperature: 20.71,
            maxScreenAirTemp: 21.41,
            minScreenAirTemp: 20.7,
            screenDewPointTemperature: 5.31,
            feelsLikeTemperature: 17.57,
            windSpeed10m: 4.75,
            windDirectionFrom10m: 302,
            windGustSpeed10m: 9.04,
            max10mWindGust: 9.97,
            visibility: 38010,
            screenRelativeHumidity: 37.19,
            mslp: 102430,
            uvIndex: 1,
            significantWeatherCode: 1,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-05T20:00Z',
            screenTemperature: 19.86,
            maxScreenAirTemp: 20.71,
            minScreenAirTemp: 19.85,
            screenDewPointTemperature: 5.88,
            feelsLikeTemperature: 17.13,
            windSpeed10m: 4.23,
            windDirectionFrom10m: 302,
            windGustSpeed10m: 8.15,
            max10mWindGust: 9.56,
            visibility: 36906,
            screenRelativeHumidity: 40.8,
            mslp: 102510,
            uvIndex: 0,
            significantWeatherCode: 0,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-05T21:00Z',
            screenTemperature: 18.96,
            maxScreenAirTemp: 19.86,
            minScreenAirTemp: 18.94,
            screenDewPointTemperature: 6.35,
            feelsLikeTemperature: 16.62,
            windSpeed10m: 3.93,
            windDirectionFrom10m: 297,
            windGustSpeed10m: 7.67,
            max10mWindGust: 9.23,
            visibility: 36626,
            screenRelativeHumidity: 44.41,
            mslp: 102578,
            uvIndex: 0,
            significantWeatherCode: 0,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-05T22:00Z',
            screenTemperature: 18.14,
            maxScreenAirTemp: 18.96,
            minScreenAirTemp: 18.13,
            screenDewPointTemperature: 6.87,
            feelsLikeTemperature: 16.19,
            windSpeed10m: 3.58,
            windDirectionFrom10m: 295,
            windGustSpeed10m: 7.08,
            max10mWindGust: 8.01,
            visibility: 35949,
            screenRelativeHumidity: 48.49,
            mslp: 102628,
            uvIndex: 0,
            significantWeatherCode: 0,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-05T23:00Z',
            screenTemperature: 17.27,
            maxScreenAirTemp: 18.14,
            minScreenAirTemp: 17.27,
            screenDewPointTemperature: 7.18,
            feelsLikeTemperature: 15.62,
            windSpeed10m: 3.36,
            windDirectionFrom10m: 295,
            windGustSpeed10m: 6.73,
            max10mWindGust: 7.71,
            visibility: 35664,
            screenRelativeHumidity: 52.24,
            mslp: 102648,
            uvIndex: 0,
            significantWeatherCode: 0,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-06T00:00Z',
            screenTemperature: 16.46,
            maxScreenAirTemp: 17.27,
            minScreenAirTemp: 16.45,
            screenDewPointTemperature: 7.59,
            feelsLikeTemperature: 15.28,
            windSpeed10m: 2.73,
            windDirectionFrom10m: 287,
            windGustSpeed10m: 5.53,
            max10mWindGust: 6.87,
            visibility: 34176,
            screenRelativeHumidity: 56.37,
            mslp: 102661,
            uvIndex: 0,
            significantWeatherCode: 0,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-06T01:00Z',
            screenTemperature: 15.83,
            maxScreenAirTemp: 16.46,
            minScreenAirTemp: 15.81,
            screenDewPointTemperature: 7.96,
            feelsLikeTemperature: 15.03,
            windSpeed10m: 2.2,
            windDirectionFrom10m: 277,
            windGustSpeed10m: 4.57,
            max10mWindGust: 5.75,
            visibility: 31415,
            screenRelativeHumidity: 60.14,
            mslp: 102650,
            uvIndex: 0,
            significantWeatherCode: 0,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-06T02:00Z',
            screenTemperature: 15.21,
            maxScreenAirTemp: 15.83,
            minScreenAirTemp: 15.19,
            screenDewPointTemperature: 8.24,
            feelsLikeTemperature: 14.62,
            windSpeed10m: 1.93,
            windDirectionFrom10m: 256,
            windGustSpeed10m: 3.92,
            max10mWindGust: 4.56,
            visibility: 27490,
            screenRelativeHumidity: 63.68,
            mslp: 102638,
            uvIndex: 0,
            significantWeatherCode: 0,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-06T03:00Z',
            screenTemperature: 14.55,
            maxScreenAirTemp: 15.21,
            minScreenAirTemp: 14.55,
            screenDewPointTemperature: 8.42,
            feelsLikeTemperature: 13.99,
            windSpeed10m: 1.92,
            windDirectionFrom10m: 246,
            windGustSpeed10m: 3.83,
            max10mWindGust: 4.16,
            visibility: 24260,
            screenRelativeHumidity: 67.14,
            mslp: 102627,
            uvIndex: 0,
            significantWeatherCode: 0,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-06T04:00Z',
            screenTemperature: 14.09,
            maxScreenAirTemp: 14.55,
            minScreenAirTemp: 14.08,
            screenDewPointTemperature: 8.6,
            feelsLikeTemperature: 13.61,
            windSpeed10m: 1.84,
            windDirectionFrom10m: 247,
            windGustSpeed10m: 3.62,
            max10mWindGust: 3.93,
            visibility: 22901,
            screenRelativeHumidity: 69.93,
            mslp: 102617,
            uvIndex: 0,
            significantWeatherCode: 0,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-06T05:00Z',
            screenTemperature: 13.89,
            maxScreenAirTemp: 14.09,
            minScreenAirTemp: 13.84,
            screenDewPointTemperature: 8.69,
            feelsLikeTemperature: 13.46,
            windSpeed10m: 1.76,
            windDirectionFrom10m: 240,
            windGustSpeed10m: 3.44,
            max10mWindGust: 3.44,
            visibility: 19951,
            screenRelativeHumidity: 71.28,
            mslp: 102625,
            uvIndex: 1,
            significantWeatherCode: 1,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-06T06:00Z',
            screenTemperature: 13.88,
            maxScreenAirTemp: 13.89,
            minScreenAirTemp: 13.73,
            screenDewPointTemperature: 8.78,
            feelsLikeTemperature: 13.39,
            windSpeed10m: 1.84,
            windDirectionFrom10m: 239,
            windGustSpeed10m: 3.08,
            max10mWindGust: 3.08,
            visibility: 19257,
            screenRelativeHumidity: 71.71,
            mslp: 102630,
            uvIndex: 1,
            significantWeatherCode: 1,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-06T07:00Z',
            screenTemperature: 14.89,
            maxScreenAirTemp: 14.9,
            minScreenAirTemp: 13.88,
            screenDewPointTemperature: 8.88,
            feelsLikeTemperature: 14.38,
            windSpeed10m: 1.88,
            windDirectionFrom10m: 241,
            windGustSpeed10m: 3.41,
            max10mWindGust: 3.41,
            visibility: 19939,
            screenRelativeHumidity: 67.8,
            mslp: 102627,
            uvIndex: 2,
            significantWeatherCode: 1,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-06T08:00Z',
            screenTemperature: 16.14,
            maxScreenAirTemp: 16.17,
            minScreenAirTemp: 14.89,
            screenDewPointTemperature: 8.95,
            feelsLikeTemperature: 15.67,
            windSpeed10m: 1.8,
            windDirectionFrom10m: 244,
            windGustSpeed10m: 3.62,
            max10mWindGust: 3.62,
            visibility: 22731,
            screenRelativeHumidity: 62.79,
            mslp: 102629,
            uvIndex: 4,
            significantWeatherCode: 1,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-06T09:00Z',
            screenTemperature: 17.49,
            maxScreenAirTemp: 17.49,
            minScreenAirTemp: 16.14,
            screenDewPointTemperature: 8.78,
            feelsLikeTemperature: 16.85,
            windSpeed10m: 1.98,
            windDirectionFrom10m: 252,
            windGustSpeed10m: 4.34,
            max10mWindGust: 4.34,
            visibility: 28025,
            screenRelativeHumidity: 56.78,
            mslp: 102619,
            uvIndex: 5,
            significantWeatherCode: 1,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-06T10:00Z',
            screenTemperature: 18.66,
            maxScreenAirTemp: 18.66,
            minScreenAirTemp: 17.49,
            screenDewPointTemperature: 8.05,
            feelsLikeTemperature: 17.73,
            windSpeed10m: 2.12,
            windDirectionFrom10m: 248,
            windGustSpeed10m: 4.72,
            max10mWindGust: 4.72,
            visibility: 30361,
            screenRelativeHumidity: 50.75,
            mslp: 102564,
            uvIndex: 5,
            significantWeatherCode: 1,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-06T11:00Z',
            screenTemperature: 19.87,
            maxScreenAirTemp: 19.87,
            minScreenAirTemp: 18.66,
            screenDewPointTemperature: 7.45,
            feelsLikeTemperature: 18.72,
            windSpeed10m: 2.17,
            windDirectionFrom10m: 248,
            windGustSpeed10m: 5.12,
            max10mWindGust: 5.12,
            visibility: 33366,
            screenRelativeHumidity: 45.25,
            mslp: 102498,
            uvIndex: 6,
            significantWeatherCode: 3,
            precipitationRate: 0.0,
            totalPrecipAmount: 0.0,
            totalSnowAmount: 0,
            probOfPrecipitation: 0,
          },
          {
            time: '2025-08-06T12:00Z',
            screenTemperature: 21.04,
            screenDewPointTemperature: 6.83,
            feelsLikeTemperature: 19.75,
            windSpeed10m: 2.21,
            windDirectionFrom10m: 248,
            windGustSpeed10m: 5.33,
            visibility: 34500,
            screenRelativeHumidity: 39.97,
            mslp: 102439,
            uvIndex: 7,
            significantWeatherCode: 3,
            precipitationRate: 0.0,
            probOfPrecipitation: 0,
          },
        ],
      },
    },
  ],
  parameters: [
    {
      totalSnowAmount: {
        type: 'Parameter',
        description: 'Total Snow Amount Over Previous Hour',
        unit: {
          label: 'millimetres',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'mm',
          },
        },
      },
      screenTemperature: {
        type: 'Parameter',
        description: 'Screen Air Temperature',
        unit: {
          label: 'degrees Celsius',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'Cel',
          },
        },
      },
      visibility: {
        type: 'Parameter',
        description: 'Visibility',
        unit: {
          label: 'metres',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'm',
          },
        },
      },
      windDirectionFrom10m: {
        type: 'Parameter',
        description: '10m Wind From Direction',
        unit: {
          label: 'degrees',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'deg',
          },
        },
      },
      precipitationRate: {
        type: 'Parameter',
        description: 'Precipitation Rate',
        unit: {
          label: 'millimetres per hour',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'mm/h',
          },
        },
      },
      maxScreenAirTemp: {
        type: 'Parameter',
        description: 'Maximum Screen Air Temperature Over Previous Hour',
        unit: {
          label: 'degrees Celsius',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'Cel',
          },
        },
      },
      feelsLikeTemperature: {
        type: 'Parameter',
        description: 'Feels Like Temperature',
        unit: {
          label: 'degrees Celsius',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'Cel',
          },
        },
      },
      screenDewPointTemperature: {
        type: 'Parameter',
        description: 'Screen Dew Point Temperature',
        unit: {
          label: 'degrees Celsius',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'Cel',
          },
        },
      },
      screenRelativeHumidity: {
        type: 'Parameter',
        description: 'Screen Relative Humidity',
        unit: {
          label: 'percentage',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: '%',
          },
        },
      },
      windSpeed10m: {
        type: 'Parameter',
        description: '10m Wind Speed',
        unit: {
          label: 'metres per second',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'm/s',
          },
        },
      },
      probOfPrecipitation: {
        type: 'Parameter',
        description: 'Probability of Precipitation',
        unit: {
          label: 'percentage',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: '%',
          },
        },
      },
      max10mWindGust: {
        type: 'Parameter',
        description: 'Maximum 10m Wind Gust Speed Over Previous Hour',
        unit: {
          label: 'metres per second',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'm/s',
          },
        },
      },
      significantWeatherCode: {
        type: 'Parameter',
        description: 'Significant Weather Code',
        unit: {
          label: 'dimensionless',
          symbol: {
            value: 'https://datahub.metoffice.gov.uk/',
            type: '1',
          },
        },
      },
      minScreenAirTemp: {
        type: 'Parameter',
        description: 'Minimum Screen Air Temperature Over Previous Hour',
        unit: {
          label: 'degrees Celsius',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'Cel',
          },
        },
      },
      totalPrecipAmount: {
        type: 'Parameter',
        description: 'Total Precipitation Amount Over Previous Hour',
        unit: {
          label: 'millimetres',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'mm',
          },
        },
      },
      mslp: {
        type: 'Parameter',
        description: 'Mean Sea Level Pressure',
        unit: {
          label: 'pascals',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'Pa',
          },
        },
      },
      windGustSpeed10m: {
        type: 'Parameter',
        description: '10m Wind Gust Speed',
        unit: {
          label: 'metres per second',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: 'm/s',
          },
        },
      },
      uvIndex: {
        type: 'Parameter',
        description: 'UV Index',
        unit: {
          label: 'dimensionless',
          symbol: {
            value: 'http://www.opengis.net/def/uom/UCUM/',
            type: '1',
          },
        },
      },
    },
  ],
};

export default stormTestHourlyForecast;
