/**
 * TypeScript types for UK Bank Holidays API response
 * API: https://www.gov.uk/bank-holidays.json
 *
 * Generated by Claude Code 1.0.73
 * May contain hallucinations,
 * Bit of an experiment tech spike to test LLM AI generation of something:
 *   * Low risk - types.
 *   * Tedious that a computer an probably do better.
 *
 */

export interface BankHoliday {
  /** The name/title of the bank holiday */
  title: string;
  /** Date in YYYY-MM-DD format */
  date: string;
  /** Additional notes about the holiday (optional) */
  notes: string;
  /** Whether bunting is recommended for this holiday */
  bunting: boolean;
}

export interface DivisionHolidays {
  /** The UK division/region name */
  division: string;
  /** Array of bank holiday events for this division */
  events: BankHoliday[];
}

export interface UKBankHolidays {
  /** Bank holidays for England and Wales */
  'england-and-wales': DivisionHolidays;
  /** Bank holidays for Scotland */
  scotland: DivisionHolidays;
  /** Bank holidays for Northern Ireland */
  'northern-ireland': DivisionHolidays;
}

/**
 * Type guard to check if an object is a valid UKBankHolidays response
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function isUKBankHolidays(obj: any): obj is UKBankHolidays {
  return (
    obj &&
    typeof obj === 'object' &&
    obj['england-and-wales'] &&
    obj.scotland &&
    obj['northern-ireland'] &&
    typeof obj['england-and-wales'].division === 'string' &&
    Array.isArray(obj['england-and-wales'].events) &&
    typeof obj.scotland.division === 'string' &&
    Array.isArray(obj.scotland.events) &&
    typeof obj['northern-ireland'].division === 'string' &&
    Array.isArray(obj['northern-ireland'].events)
  );
}

/**
 * Type guard to check if an object is a valid BankHoliday
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function isBankHoliday(obj: any): obj is BankHoliday {
  return (
    obj &&
    typeof obj === 'object' &&
    typeof obj.title === 'string' &&
    typeof obj.date === 'string' &&
    typeof obj.notes === 'string' &&
    typeof obj.bunting === 'boolean'
  );
}
